### ISSUE TITLE
Action auto-install后ibm页面报错

### ISSUE THREAD

**Issue by Livan-91** [artxia/IBM-flowerss-bot#1]
![image](https://user-images.githubusercontent.com/61422668/110266286-69e27d80-7ff8-11eb-83e9-14fce7d46060.png)

**Comment by artxia** [comment]
- 如果是第一次安装出现这样的问题，建议完全删掉容器，仔细检查容器名和bot的配置文件，并重装。
- 如果是安装成功且运行一段时间后出现这样的情况，直接重启容器应该就可以了。不行也可以删掉重装。

再不行，可以点日志，看到详细日志，贴出来。
你现在这个截图什么也看不到。

**Comment by Livan-91** [comment]
> * 如果是第一次安装出现这样的问题，建议完全删掉容器，仔细检查容器名和bot的配置文件，并重装。
> * 如果是安装成功且运行一段时间后出现这样的情况，直接重启容器应该就可以了。不行也可以删掉重装。
> 
> 再不行，可以点日志，看到详细日志，贴出来。
> 你现在这个截图什么也看不到。

谢谢，明白了，过会儿再检查下配置文件
